BOOTMAGIC_ENABLE = no
AUDIO_SUPPORTED = no        # Audio is not supported
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
LTO_ENABLE = yes
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
REPEAT_KEY_ENABLE = yes

SPLIT_KEYBOARD = yes

SERIAL_DRIVER = vendor
